In [6]:
#Day 1 Numpy & operations

In [7]:
import numpy as np

In [8]:
#create 1d,2d,3d arrays

In [9]:
a =np.array([1,2,3,4])

In [10]:
b =np.array([[2,4,6],[8,10,12]])

In [11]:
c =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [12]:
print(a)

[1 2 3 4]


In [13]:
print(b)

[[ 2  4  6]
 [ 8 10 12]]


In [14]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
#arthematic operators

In [16]:
print(a+5)

[6 7 8 9]


In [17]:
print(a-5)

[-4 -3 -2 -1]


In [18]:
print(a*5)

[ 5 10 15 20]


In [19]:
print(a/5)

[0.2 0.4 0.6 0.8]


In [20]:
#Functions

In [21]:
print(np.mean(a)) #mean

2.5


In [22]:
print(np.sum(b))#sum

42


In [23]:
print(np.std(c)) #Standard deviation

2.29128784747792


In [24]:
#Arange

In [25]:
c =np.arange(10,21)
print(c)

[10 11 12 13 14 15 16 17 18 19 20]


In [26]:
print(b.shape)

(2, 3)


In [27]:
c=np.linspace(10,20)

In [28]:
c

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [29]:
print(np.max(a))

4


In [30]:
print(np.min(b))

2
